estimator: 
    - 'Pk'

multipoles: 
    - '0'
    - '2'
    - '4'

cov_mock_nb: 1000

k_edges:
    'Pk':
        '0':
            - .01
            - .15
        '2':
            - .01
            - .15
        '4':
            - .01
            - .15

data_dir: '/home/rneveux/mocks/fake/'
    
name_file:
    'Pk':
        '0': 'pk0_rsd_kpk'
        '2': 'pk2_rsd_kpk'
        '4': 'pk4_rsd_kpk'
        
cov_file: '/home/rneveux/covariance_matrix/cov_FirstGenMocks_EZmock_Cubic_LRG_z0.800_pk0_pk2_pk4.npy'

rescale: false

h_fid: .6736
omega_b_fid: .02237
omega_cdm_fid: .12
n_s_fid: .9649
A_s_fid: 2.0830e-9

prior: 
    'b1':
        'type': 'Uni'
        'lim':
            - 0
            - 10
    'b2':
        'type': 'Uni'
        'lim':
            - -5
            - 5
    'bG2':
        'type': 'Uni'
        'lim':
            - -5
            - 5
    'bGamma3':
        'type': 'Uni'
        'lim':
            - -5
            - 5
    'c0':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'c1':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'c2':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'ch':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'Pshot':
        'type': 'Uni'
        'lim':
            - -5
            - 10
    'a0':
        'type': 'Uni'
        'lim':
            - -5
            - 10
    'omega_cdm':
        'type': 'Uni'
        'lim':
            - .102
            - .139
    'omega_b':
        'type': 'Uni'
        'lim':
            - .0207
            - .0242
    'h':
        'type': 'Uni'
        'lim':
            - .575
            - .747
    'n_s':
        'type': 'Uni'
        'lim':
            - .91
            - 1.02
    'ln10^{10}A_s':
        'type': 'Uni'
        'lim':
            - 2.78
            - 3.32

z_eff: .8

mean_density: 1.0e-3

save_directory: '/home/rneveux/fit_results/Fake/z0.800/'

spec: 'all'

multipoles_to_use: false

window: false
