estimator: 
    - 'Pk'
    - 'Bk'

multipoles: 
    - '0'
    - '2'
    - '000'
    - '202'

k_edges:
    'Pk':
        '0':
            - .02
            - .18
        '2':
            - .02
            - .18
    'Bk':
        '000':
            - .02
            - .08
        '202':
            - .02
            - .08

data_dir: '/global/u2/c/cguandal/TripoSH-Factory/example/'

name_file:
    'Pk':
        '0': 'pk0_CubicBox_rsd_phmean_kpk'
        '2': 'pk2_CubicBox_rsd_phmean_kpk'
    'Bk':
        '000': 'bk000_CubicBox_rsd_phmean_kbk'
        '202': 'bk202_CubicBox_rsd_phmean_kbk'
        
cov_file: '/global/u2/c/cguandal/TripoSH-Factory/Data/cov.npy'

cov_mock_nb: 1000

rescale: 0.04

h_fid: .6736
omega_b_fid: .02237
omega_cdm_fid: .12
n_s_fid: .9649
A_s_fid: 2.0830e-9

prior: 
    'b1':
        'type': 'Uni'
        'lim':
            - 0
            - 4
    'b2':
        'type': 'Uni'
        'lim':
            - -15
            - 15
    'bG2':
        'type': 'Uni'
        'lim':
            - -15
            - 15
    'bGamma3':
        'type': 'Uni'
        'lim':
            - -15
            - 15
    'c0':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'c2pp':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'ch':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'c1':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'c2':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'Pshot':
        'type': 'Uni'
        'lim':
            - -10
            - 10
    'a0':
        'type': 'Uni'
        'lim':
            - -10
            - 10
    'Bshot':
        'type': 'Uni'
        'lim':
            - -10
            - 10
    'fnlequi':
        'type': 'Fix'
        'lim': 0
    'fnlortho_LSS':
        'type': 'Fix'
        'lim': 0
    'omega_cdm':
        'type': 'Uni'
        'lim': #.12
            - .102
            - .139
    'omega_b':
        'type': 'Gauss'
        'lim': #.02237
            - .02237
            - .00037
    'h':
        'type': 'Uni'
        'lim': #.6736
            - .575
            - .747
    'n_s':
        'type': 'Fix'
        'lim': .9649
    'ln10^{10}A_s':
        'type': 'Uni'
        'lim': #3.0364
            - 2.78
            - 3.32

z_eff: 0.8

mean_density: 1.0e-3

save_directory: '/global/u2/c/cguandal/TripoSH-Factory/Results/Test/Bispectrum/'

spec: 'PkBk_TEST_CubicBox_LRG_z0.800_NoShotNoise'

multipoles_to_use:
    'Bk':
        - '000'
        - '202'

cache_path: '/global/u2/c/cguandal/TripoSH-Factory/Data/z0.8/'

window: false

sampler: 'poco'

direct_classpt: false