estimator: 
    - 'Pk'
    - 'Bk'

multipoles: 
    - '0'
    - '2'
    - '4'
    - '000'
    - '202'

cov_mock_nb: 1000

k_edges:
    'Pk':
        '0':
            - .02
            - .18
        '2':
            - .02
            - .18
        '4':
            - .02
            - .18
    'Bk':
        '000':
            - .02
            - .08
        '202':
            - .02
            - .08

data_dir: '/home/swang/share/rneveux/FirstGenMocks_AbacusSummit/CubicBox/LRG/z0.800/stable/'
    
name_file:
    'Pk':
        '0': 'powspec/pk0_CubicBox_rsd_phmean_kpk' #'powspec/pk0_CubicBox_rsd_phmean_kpksubshot'
        '2': 'powspec/pk2_CubicBox_rsd_phmean_kpk'
        '4': 'powspec/pk4_CubicBox_rsd_phmean_kpk'
    'Bk':
        '000': 'bispec/bk000_CubicBox_rsd_phmean_kbk' #'bispec/bk000_diag_CubicBox_rsd_phmean_kbksubshot'
        '202': 'bispec/bk202_CubicBox_rsd_phmean_kbk' #'bispec/bk202_diag_CubicBox_rsd_phmean_kbksubshot'
        
cov_file: '/home/rneveux/covariance_matrix/cov_FirstGenMocks_EZmock_Cubic_LRG_z0.800_pk0_pk2_pk4_bk000_bk202.npy'

rescale: .04

h_fid: .6736
omega_b_fid: .02237
omega_cdm_fid: .12
n_s_fid: .9649
A_s_fid: 2.0830e-9

prior: 
    'b1':
        'type': 'Uni'
        'lim':
            - 1
            - 4
    'b2':
        'type': 'Uni'
        'lim':
            - -10
            - 10
    'bG2':
        'type': 'Uni'
        'lim':
            - -10
            - 10
    'bGamma3':
        'type': 'Uni'
        'lim':
            - -10
            - 10
    'c0':
        'type': 'Uni'
        'lim':
            - -100
            - 100
    'c2pp':
        'type': 'Uni'
        'lim':
            - -100
            - 100
    'c4pp':
        'type': 'Uni'
        'lim':
            - -100
            - 100
    'ch':
        'type': 'Uni'
        'lim':
            - -2000
            - 2000
    'c1':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'c2':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'Pshot':
        'type': 'Uni'
        'lim':
            - -10
            - 10
    'a0':
        'type': 'Uni'
        'lim':
            - -100
            - 100
    'Bshot':
        'type': 'Uni'
        'lim':
            - -10
            - 10
    'fnlequi':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'fnlortho_LSS':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'omega_cdm':
        'type': 'Fix'
        'lim': .12
    'omega_b':
        'type': 'Fix'
        'lim': .02237
    'h':
        'type': 'Fix'
        'lim': .6736
    'n_s':
        'type': 'Fix'
        'lim': .9649
    'ln10^{10}A_s':
        'type': 'Fix'
        'lim': 3.0364

z_eff: .8

mean_density: 1.0e-3

save_directory: '/home/rneveux/fit_results/FirstGenMocks_AbacusSummit/CubicBox/LRG/z0.800/'

spec: 'kmin2_kmaxpk18_kmaxbk8_rescaled25_fnl_noprior'

multipoles_to_use:
    'Bk':
        - '000'
        - '202'
        
k_dir: '/home/rneveux/kernels/bk/z.8/k_1_20_test_h_nowiggle'

window: false

sampler: 'poco'